[package]
name = "zefir-os"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "zefir-os"
test = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"