[package]
name = "zefir-os"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "zefir-os"
test = false

[dependencies]
bootloader = "0.9.8"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
